// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    NButton: typeof import("naive-ui")["NButton"];
    NList: typeof import("naive-ui")["NList"];
    NListItem: typeof import("naive-ui")["NListItem"];
    NModal: typeof import("naive-ui")["NModal"];
    NSpin: typeof import("naive-ui")["NSpin"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}
